name: Throw On Error

# doc:               https://docs.github.com/en/actions
# variables:         https://docs.github.com/en/actions/learn-github-actions/environment-variables
# secrets:           https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-17
# env:               https://docs.github.com/en/actions/learn-github-actions/environment-variables
# reusable workflow: https://docs.github.com/en/actions/learn-github-actions/reusing-workflows#access-to-reusable-workflows

on: 
  workflow_call:
  
jobs:
  on-failure:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Message
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        run: echo 'Stopped - Dependencies failure'

      - name: Throw
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        uses: actions/github-script@v5
        with:
          script: |
              core.setFailed('Stopped because of previous failure')

      - name: Cancel Message
        if: ${{ github.event.workflow_run.conclusion == 'cancelled' }}
        run: echo 'Cancelled'

      - name: Throw
        if: ${{ github.event.workflow_run.conclusion == 'cancelled' }}
        uses: actions/github-script@v5
        with:
          script: |
              core.setFailed('Cancelled because of previous cancellation')
